wercker.yml

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -1,39 +1,38 @@
-name: java
-        version: 0.1.3
-        inherits: wercker/ubuntu12.04-webessentials@0.0.5
-        type: main
-        platform: ubuntu@12.04
-        description: Wercker box for Java development
-        packages:
-        - oracle-java8
-        script: |-
-        # Remove java from base box
-        sudo apt-get purge openjdk-\* icedtea-\* icedtea6-\*
+name: java8-oracle
+version: 0.0.1
+description: Java8 box provisioned with the Oracle distribution via the webupd8team ppa. Comes with maven, ant and gradle 
+keywords:
+  - java
+  - ant
+  - maven
+  - oracle
+type: main
+os: ubuntu@12.04
+env:
+  SBT_OPTS: -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M
+  IVY_CACHE_DIR: '"$WERCKER_CACHE_DIR/ivy"'
+script: |-
+  # Install Java 8 
+  sudo apt-get update
+  sudo apt-get install python-software-properties curl wget -y
+  sudo add-apt-repository ppa:webupd8team/java -y
+  sudo apt-get update
+  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
+  sudo apt-get install oracle-java8-installer -qq
+  sudo apt-get install oracle-java8-set-default -y
 
-        # Assert that java is not available anymore
-        ! type java || { echo "I expected java to be not available. Java version is: $(java -version). Aborting."; exit 1; }
+  # Install maven
+  sudo apt-get install maven
 
-        # Add webupd8 team repository that contains the 3 major oracle-java versions
-        sudo add-apt-repository ppa:webupd8team/java -y
-        sudo apt-get update
+  # Install Gradle
+  sudo add-apt-repository ppa:cwchien/gradle -y
+  sudo apt-get update
+  sudo apt-get install gradle -y
 
-        # Accept the oracle license
-        echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
-        echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
+  # Install ant
+  sudo apt-get install ant ant-contrib ivy ivy-doc -y -qq
 
-        # Install oracle-java8
-        sudo apt-get install oracle-java8-installer -y -qq
-
-        # We should have java again
-        type java || { echo "I expected java to be available after oracle-java8-installer installation. Aborting."; exit 1; }
-
-        # Install ant
-        sudo apt-get install ant ant-contrib ivy ivy-doc -y -qq
-
-        # We should have ant and ivy available
-        type ant || { echo "I expected ant to be available. Aborting."; exit 1; }
-
-        # Install maven
-        sudo apt-get install maven -y -qq
-
-        type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
+   # We should have ant and ivy available
+  type ant || { echo "I expected ant to be available. Aborting."; exit 1; }
+  type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
+  type gradle || { echo "No gradle command found...aborting"; exit 1; }
